//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowLada.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Car_In_Supply = new HashSet<Car_In_Supply>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int id_Car { get; set; }
        public string Model { get; set; }
        public int id_Color { get; set; }
        public int id_Body { get; set; }
        public int id_Drive { get; set; }
        public int Engine_power { get; set; }
        public decimal Cost { get; set; }
        public byte[] Image { get; set; }
        public int CountCar { get; set; }
    
        public virtual Body Body { get; set; }
        public virtual Color Color { get; set; }
        public virtual Drive Drive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car_In_Supply> Car_In_Supply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
