//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowLada.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int id_Sale { get; set; }
        public Nullable<int> id_Worker { get; set; }
        public Nullable<int> id_Branch { get; set; }
        public Nullable<int> id_Car { get; set; }
        public Nullable<System.DateTime> Date_sale { get; set; }
        public Nullable<int> id_Client { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
